# sample configuration file for sharedis

desc = "sample configuration for sharedis"

[sharedis]
loglevel = "info"
logpath = "/data/sharedis/log/sharedis.log"

[backend]
thrift_port = 9090
thrift_timeout_ms = 3000
prometheus_port = 10109
#tikv placement driver addresses
pds = "10.20.14.42:2379,10.20.14.243:2379,10.20.0.176:2379"
